---
title: "Response function summary"
output: pdf_document
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
```

```{r rfx_sum}
RFxSum <- read_csv("Response_Fx_Summary.csv")

table(RFxSum$Pathway)
table(RFxSum$System)

RFxSum %>% filter(System != "Other") %>% 
  group_by(Chemical, Pathway) %>% 
  summarise(n = n()) %>% 
  spread(key = Pathway, value = n) %>% 
  rename("bottom_up" = !!names(.[2]),
         "direct_larvae" = !!names(.[3]),
         "direct_snail" = !!names(.[4]),
         "top_down" = !!names(.[5])) %>% 
  mutate(num_records = sum(bottom_up, direct_larvae, 
                           direct_snail, top_down, na.rm = TRUE)) %>% 
  filter(num_records > 1) %>% 
  select(-num_records) %>% 
  replace_na(list("bottom_up" = 0,
                  "direct_larvae" = 0,
                  "direct_snail" = 0,
                  "top_down" = 0)) %>% 
  knitr::kable()
```

```{r}
# For chemicals with adequate data, e.g. those that have evidence for approximately all hypthesized pathways, find those with multiple studies and determine which study (e.g. response function) is preferred
RFx_multis <- RFxSum %>% filter(Chemical %in% c("Atrazine", "Butachlor", "Butralin", 
                                                "Chlorpyrifos", "Glyphosate", "Malathion", "Profenofos") &
                                  System != "Other") %>% 
  group_by(Chemical, parameter, System) %>% 
  summarise(nfx = n(),
            matches = paste(Study, collapse = " ; "),
            species = paste(Species, collapse = " ; ")) %>% filter(nfx > 1)


RFxSum <- RFxSum %>% full_join(RFx_multis, by = c("Chemical", "parameter", "System"))  
```

```{r nawqa_sum}
#Get NAWQA data, functions, and response functions summary
load("~/RemaisWork/Schisto/R Codes/ag_schist/Agrochemical_Review/Sims/Data/NAWQA_dat_functions.RData")

nawqa_sum <- t(sapply(chems, get_nawqa_sum))
  colnames(nawqa_sum) <- c("nawqa.50", "nawqa.25", "nawqa.75")
  
study_sum <- RFxSum %>% 
  inner_join(as.data.frame(cbind(Chemical = chems, nawqa_sum)), by = "Chemical") %>%   
  group_by(study_long) %>% 
  summarise(Chemicals = paste(unique(Chemical), collapse = ","),
            #Chemical_Class = paste(unique(Class), collapse = ","),
            #Peak_EEC = paste(unique(eec), collapse = ","),
            #NAWQA.50 = paste(unique(nawqa.50), collapse = ","),
            #NAWQA.25 = paste(unique(nawqa.25), collapse = ","),
            #NAWQA.75 = paste(unique(nawqa.75), collapse = ","),
            Species = paste(unique(Species), collapse = ","),
            Model_parameter = paste(unique(parameter), collapse = ","))
```

```{r eec_sum}
RFxSum %>% group_by(Chemical) %>% 
  summarise(EEC = mean(eec),
            Source = first(eec_source)) %>% 
  knitr::kable()
```

